# coding: utf-8

"""
    flow ai sdk

    This is the Flow AI SDK, used to interact with a Flow server. Flow is an AI foundational platform that exposes common high-level AI tool functionality.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flow.models.status200_response import Status200Response

class TestStatus200Response(unittest.TestCase):
    """Status200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Status200Response:
        """Test Status200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Status200Response`
        """
        model = Status200Response()
        if include_optional:
            return Status200Response(
                version = '1.1.0'
            )
        else:
            return Status200Response(
        )
        """

    def testStatus200Response(self):
        """Test Status200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
