openapi: 3.0.0
info:
  title: flow ai sdk
  description: >-
    This is the Flow AI SDK, used to interact with a Flow server. Flow is an
    AI foundational platform that exposes common high-level AI tool functionality.
  version: 0.0.1
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: user
    description: Operations about user
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    ErrResponse:
      type: object
      properties:
        err:
          type: string
        msg:
          type: string
        fields:
          type: object
          additionalProperties:
            type: string
    StatusResponse:
      type: object
      properties:
        version:
          type: string
          description: The current version of the Flow AI Server.
          example: "1.1.0"
security:
  - BearerAuth: []
paths:
  /status:
    get:
      summary: Get API status
      operationId: status
      responses:
        "200":
          description: OK - The API is running and returns the current version.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrResponse"
