# coding: utf-8

"""
    flow ai sdk

    This is the Flow AI SDK, used to interact with a Flow server. Flow is an AI foundational platform that exposes common high-level AI tool functionality.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flow.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_status(self) -> None:
        """Test case for status

        Get API status
        """
        pass


if __name__ == '__main__':
    unittest.main()
